import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { describe, it } from 'node:test'

const read = path => readFile(new URL(path, import.meta.url), 'utf8')

describe('câblage du prototype de compte pseudonyme', () => {
  it('protège la page personnelle et la garde hors index', async () => {
    const page = await read('../app/pages/my-page.vue')
    const space = await read('../app/components/learner/LearnerSpace.vue')
    assert.match(page, /middleware:\s*'learner-auth'/u)
    assert.match(page, /noindex, nofollow/u)
    assert.match(page, /<LearnerSpace/u)
    assert.match(space, /\{\{ copy\.hello \}\} \{\{ displayUsername \}\}/u)
  })

  it('garde les deux routes hors des statistiques', async () => {
    const analytics = await read('../app/plugins/analytics.client.ts')
    assert.match(analytics, /normalized === '\/signin' \|\| normalized === '\/my-page'/u)
    const robots = await read('../public/robots.txt')
    assert.match(robots, /Disallow: \/fr\/signin/u)
    assert.match(robots, /Disallow: \/fr\/my-page/u)
  })

  it('applique le contrôle de même origine aux mutations du compte', async () => {
    const security = await read('../server/middleware/security.ts')
    assert.match(security, /path\.startsWith\('\/api\/learner\/'\)/u)
    assert.match(security, /https:\/\/challenges\.cloudflare\.com/u)
  })

  it('sépare les tables et cookies élèves de ceux de l’administration', async () => {
    const migration = await read('../server/plugins/learner-accounts-migration.ts')
    const session = await read('../server/utils/learner-session.ts')
    assert.match(migration, /CREATE TABLE IF NOT EXISTS learner_accounts/u)
    assert.match(migration, /UNIQUE KEY uq_learner_accounts_username/u)
    assert.match(migration, /CREATE TABLE IF NOT EXISTS learner_challenge_runs/u)
    assert.match(migration, /CREATE TABLE IF NOT EXISTS learner_answer_attempts/u)
    assert.match(migration, /CREATE TABLE IF NOT EXISTS learner_error_types/u)
    assert.match(migration, /CREATE TABLE IF NOT EXISTS learner_attempt_error_tags/u)
    assert.match(migration, /CREATE TABLE IF NOT EXISTS learner_skill_daily_stats/u)
    assert.match(migration, /CREATE TABLE IF NOT EXISTS learner_run_forms/u)
    assert.match(migration, /CREATE TABLE IF NOT EXISTS learner_run_questions/u)
    assert.match(migration, /CREATE TABLE IF NOT EXISTS learner_login_events/u)
    assert.match(migration, /CREATE TABLE IF NOT EXISTS learner_preferences/u)
    assert.match(session, /learner_session/u)
    assert.doesNotMatch(session, /conjugaison_session/u)
  })

  it('sépare les admins historiques des utilisateurs pseudonymes', async () => {
    const shell = await read('../app/components/admin/AdminShell.vue')
    const admins = await read('../app/pages/admin/admins.vue')
    const users = await read('../app/pages/admin/users.vue')
    const usersEndpoint = await read('../server/api/admin/users/index.get.ts')
    const subject = await read('../server/utils/learner-data-subject.ts')
    assert.match(shell, /label:\s*'Admins', path:\s*'\/admin\/admins'/u)
    assert.match(shell, /label:\s*'Utilisateurs', path:\s*'\/admin\/users'/u)
    assert.match(admins, /Créez et gérez les comptes qui peuvent accéder à l’administration/u)
    assert.doesNotMatch(admins, /prof, élève ou parent/u)
    assert.match(users, /:inspected-learner/u)
    assert.match(users, /read-only/u)
    assert.match(usersEndpoint, /FROM learner_accounts/u)
    assert.match(usersEndpoint, /ORDER BY exerciseCount DESC/u)
    assert.match(subject, /requireAdministrator\(event\)/u)
  })

  it('ouvre la connexion par défaut et préremplit seulement en développement', async () => {
    const page = await read('../app/pages/signin.vue')
    const copy = await read('../shared/i18n/learner-auth.ts')
    assert.doesNotMatch(page, /Prototype privé/u)
    assert.match(copy, /Créer un compte t’aide à mieux progresser/u)
    assert.match(copy, /tes résultats sont mémorisés/u)
    assert.match(copy, /retravailler tes fautes/u)
    assert.match(copy, /Aucun nom ni aucune adresse e-mail ne sont demandés/u)
    const endpoint = await read('../server/api/dev-learner-login.get.ts')
    const gitignore = await read('../.gitignore')
    assert.match(page, /const mode = ref<Mode>\('login'\)/u)
    assert.match(page, /copy\.signIn/u)
    assert.match(page, /copy\.create/u)
    assert.match(page, /\/api\/dev-learner-login/u)
    assert.match(endpoint, /if \(!import\.meta\.dev\)/u)
    assert.match(endpoint, /learner-login\.local\.json/u)
    assert.match(gitignore, /^learner-login\.local\.json$/mu)
  })

  it('remplace les préférences de navigation par le menu de l’élève connecté', async () => {
    const layout = await read('../app/layouts/default.vue')
    const auth = await read('../app/composables/useLearnerAuth.ts')
    assert.match(layout, /<details v-if="learner"[^>]+class="learner-menu"/u)
    assert.match(layout, /<template v-else>/u)
    assert.match(layout, /class="site-login-button"[^>]+localePath\('\/signin'\)/u)
    assert.match(layout, /\{\{ ui\('Connexion'\) \}\}/u)
    assert.match(layout, /class="theme-switch"[\s\S]*class="language-selector[^"]*"[\s\S]*class="site-login-button"/u)
    assert.doesNotMatch(layout, /theme-switch__thumb/u)
    assert.match(layout, /\.theme-switch__icon--moon\s*\{\s*opacity:\s*1;/u)
    assert.match(layout, /\.theme-switch\.is-dark \.theme-switch__icon--sun\s*\{\s*opacity:\s*1;/u)
    assert.match(layout, /learnerCopy\.history/u)
    assert.match(layout, /learnerCopy\.commonErrors/u)
    assert.match(layout, /learnerCopy\.improve/u)
    assert.match(layout, /learnerCopy\.preferences/u)
    assert.match(layout, /learnerCopy\.changeLanguage/u)
    assert.match(layout, /ui\('Changer mon mot de passe'\)/u)
    assert.match(layout, /tab=account#change-password/u)
    assert.match(layout, /ui\('Me déconnecter'\)/u)
    assert.match(layout, /closeLearnerMenuOnOutside/u)
    assert.match(layout, /document\.addEventListener\('pointerdown'/u)
    assert.match(layout, /document\.removeEventListener\('pointerdown'/u)
    assert.match(auth, /useState<LearnerUser \| null>\('learner-user'/u)
    assert.match(auth, /\/api\/learner\/me/u)
  })

  it('organise l’espace élève et permet de gérer ses données', async () => {
    const page = await read('../app/components/learner/LearnerSpace.vue')
    const copy = await read('../shared/i18n/learner-space.ts')
    const dashboard = await read('../server/api/learner/dashboard.get.ts')
    const learnerReview = await read('../server/api/learner/review.get.ts')
    const learnerProgress = await read('../server/api/learner/progress.get.ts')
    const deleteResults = await read('../server/api/learner/results.delete.ts')
    const deleteAccount = await read('../server/api/learner/account.delete.ts')
    const changePassword = await read('../server/api/learner/password.put.ts')
    assert.match(copy, /improve: 'Progresser'/u)
    assert.doesNotMatch(page, />Tendances</u)
    assert.match(page, /copy\.commonErrors/u)
    assert.match(page, /\{\{\s*copy\.commonErrors\s*\}\}\s*<\/button>[\s\S]*class="learner-tabs__primary"/u)
    assert.match(page, /\{\{ copy\.preferences \}\}/u)
    assert.match(page, /\{\{ copy\.account \}\}/u)
    assert.doesNotMatch(page, /Apprendre à ton rythme/u)
    assert.match(copy, /chooseTraining: 'Choisir mon prochain entraînement'/u)
    assert.match(copy, /reviewJourney: 'Relire mon parcours'/u)
    assert.match(copy, /errorsOverTime: 'Voir mes fautes dans le temps'/u)
    assert.doesNotMatch(page, /class="progress-metric-tabs"/u)
    assert.match(copy, /Nous n’enregistrons ni nom, ni adresse e-mail, ni date de naissance/u)
    assert.match(copy, /deleteResults: 'Supprimer mes résultats'/u)
    assert.match(copy, /deleteAccount: 'Supprimer mon compte'/u)
    assert.match(page, /id="change-password"/u)
    assert.match(page, /autocomplete="current-password"/u)
    assert.match(page, /autocomplete="new-password"/u)
    assert.match(page, /\/api\/learner\/password/u)
    assert.match(page, /role="alertdialog"/u)
    assert.match(page, /\/api\/learner\/results/u)
    assert.match(page, /\/api\/learner\/account/u)
    assert.match(deleteResults, /DELETE FROM learner_skill_daily_stats WHERE account_id = \?/u)
    assert.match(deleteResults, /DELETE FROM learner_challenge_runs WHERE account_id = \?/u)
    assert.match(deleteResults, /beginTransaction/u)
    assert.match(deleteAccount, /DELETE FROM learner_accounts WHERE id = \?/u)
    assert.match(deleteAccount, /clearLearnerSession/u)
    assert.match(changePassword, /bcrypt\.compare\(currentPassword/u)
    assert.match(changePassword, /bcrypt\.hash\(newPassword, 12\)/u)
    assert.match(changePassword, /session_version=\?/u)
    assert.match(changePassword, /DELETE FROM learner_sessions WHERE account_id=\?/u)
    assert.match(changePassword, /createLearnerSession/u)
    assert.match(changePassword, /password-account/u)
    assert.doesNotMatch(page, /Trier les formes à revoir/u)
    assert.doesNotMatch(page, /activeTab === 'review'/u)
    assert.match(learnerReview, /FROM learner_answer_attempts/u)
    assert.match(learnerReview, /a\.is_correct=0/u)
    assert.match(learnerProgress, /FROM learner_skill_daily_stats/u)
    assert.match(learnerProgress, /INNER JOIN learner_run_questions/u)
    assert.match(learnerProgress, /INNER JOIN learner_attempt_error_tags/u)
    assert.match(learnerProgress, /applicableLearnerErrorTypes/u)
    assert.match(learnerProgress, /learnerErrorDetailText/u)
    assert.match(page, /class="error-progress-examples"/u)
    assert.match(page, /copy\.seeExamples/u)
    assert.match(page, /error-progress-examples__chevron/u)
    assert.match(page, /copy\.question/u)
    assert.match(page, /copy\.yourError/u)
    assert.match(page, /copy\.correction/u)
    assert.match(page, /copy\.reason/u)
    assert.match(copy, /On compare des taux, pas des nombres\./u)
    assert.match(copy, /Une période sans occasion n’est jamais comptée comme une réussite/u)
    assert.match(page, /activeTab === 'history'/u)
    assert.match(page, /copy\.history/u)
    assert.match(page, /activeTab === 'challenges' \|\| activeTab === 'history'/u)
    assert.doesNotMatch(page, /challenge-view-tabs|challengesView/u)
    assert.match(learnerReview, /buildLearnerReview/u)
    assert.match(page, /challenge-card__description/u)
    assert.match(page, /copy\.showAll/u)
    assert.match(page, /descriptionIsTruncated\(String\(challenge\.id\)\)/u)
    assert.match(page, /element\.scrollHeight > element\.clientHeight/u)
    assert.match(page, /-webkit-line-clamp:\s*2/u)
    assert.match(page, /<h3>\{\{ challenge\.label \}\}<\/h3>/u)
    assert.match(page, /--learner-purple-copy:\s*#cdb9f6/u)
    assert.match(page, /learner-space--dark/u)
    assert.match(page, /\.review-button:hover:not\(:disabled\)/u)
    assert.doesNotMatch(page, /\{\{ challenge\.scorePercent \}\}%/u)
    assert.match(page, /copy\.retrainChallenge/u)
    assert.match(page, /copy\.sameOrder/u)
    assert.match(page, /copy\.randomOrder/u)
    assert.match(page, /shuffledQuestionOrder\(work\.challenge\.exactQuestions\)/u)
    assert.match(page, /questions fausses/u)
    assert.match(page, /work\.scope === 'same'/u)
    assert.match(page, /challenge\.exactQuestions/u)
    assert.match(page, /const preserved = \[\.\.\.work\.challenge\.retryQuestions\]/u)
    assert.match(page, /questionCount:\s*missingCount/u)
    assert.match(page, /isReview:\s*work\.scope === 'incorrect'/u)
    assert.match(page, /v-if="challenge\.unresolvedCount > 0"/u)
    assert.doesNotMatch(page, /<strong>Analyse :<\/strong>/u)
    assert.doesNotMatch(page, /<ChallengeProgressDialog/u)
    assert.match(page, /challenge-presentation-menu/u)
    assert.match(page, /position:\s*absolute/u)
    assert.match(page, /grid-template-columns:\s*repeat\(2/u)
    assert.match(page, /action-button--primary/u)
    assert.match(page, /action-button--chat/u)
    assert.match(page, /closeWorkMenuOnOutside/u)
    assert.match(page, /anchor\.closest\('\.challenge-work'\)/u)
    assert.match(page, /:style="\{ left: `\$\{workMenuLeft\}px` \}"/u)
    assert.match(page, /z-index:\s*1100/u)
    assert.doesNotMatch(page, /Questions et correction immédiate/u)
    assert.doesNotMatch(page, /Dialogue virtuel avec une aide pas à pas/u)
    assert.match(page, /<CoachPicker/u)
    assert.match(page, /<ChatExercise/u)
    assert.match(page, /progressChartSegments/u)
    assert.match(page, /bottom - progressRate\(point\.errorRate\) \/ 100 \* \(bottom - top\)/u)
    assert.match(page, /function progressGradientId/u)
    assert.match(page, /Math\.min\(10, riskRate - 10\) \/ 10/u)
    assert.match(page, /<stop offset="20%" stop-color="#ef6760" \/>/u)
    assert.match(page, /<stop offset="100%" stop-color="#ef6760" \/>/u)
    assert.match(page, /\.error-progress-chart__date-axis span\s*\{[^}]*color:\s*#fff !important;/su)
    assert.match(page, /\.error-progress-chart__date-axis span\s*\{[^}]*font:\s*400 10px/su)
    assert.match(page, /\.error-progress-chart__rate-axis span\s*\{[^}]*font:\s*400 11px/su)
    assert.match(page, /\.error-progress-chart__rate-axis\.is-errors \.is-low[\s\S]*color:\s*#3aa66f !important;/u)
    assert.match(page, /\.error-progress-chart__rate-axis\.is-errors \.is-high[\s\S]*color:\s*#ef6760 !important;/u)
    assert.match(page, /copy\.fewerErrorsBelow/u)
    assert.match(page, /learnerProgress\.minimumEvidence/u)
    assert.match(page, /:require-success="reviewRequireSuccess"/u)
    const chat = await read('../app/components/exercise/ChatExercise.vue')
    assert.match(chat, /repeatCurrentQuestion/u)
    assert.match(chat, /diagnoseCoachAgreement/u)
    assert.match(chat, /agreementDiagnostic\?\.errorKind === 'agreement'/u)
    assert.match(chat, /learnerErrorDetails/u)
    assert.match(chat, /import LearnerErrorFeedback from '~\/components\/exercise\/LearnerErrorFeedback\.vue'/u)
    assert.match(chat, /item\.errorDetails/u)
    assert.match(chat, /errorDetails:\s*currentErrorDetails/u)
    assert.match(chat, /scrollToHelpOnSmallScreen/u)
    assert.match(chat, /scroll-snap-type:\s*y mandatory/u)
    assert.match(chat, /scroll-snap-stop:\s*always/u)
    assert.match(chat, /height:\s*100dvh/u)
    assert.match(chat, /grid-auto-rows:\s*100dvh/u)
    assert.match(chat, /Glisse vers le bas pour voir l’aide/u)
    assert.match(chat, /chat-message--mobile-help-hint/u)
    const classic = await read('../app/components/exercise/ClassicExercise.vue')
    assert.match(classic, /retryMessages/u)
    assert.match(classic, /agreementError/u)
    assert.match(classic, /learnerErrorDetails/u)
    assert.match(classic, /import LearnerErrorFeedback from '~\/components\/exercise\/LearnerErrorFeedback\.vue'/u)
    assert.match(classic, /attempt\.errorDetails/u)
    assert.match(classic, /detectedErrorDetails/u)
    assert.match(classic, /<ExerciseSummaryPrintPreview/u)
    const printSummary = await read('../app/components/exercise/ExerciseSummaryPrintPreview.vue')
    assert.match(printSummary, /learnerErrorDetailText/u)
    assert.match(page, /class="challenge-history"/u)
    assert.match(page, /v-for="day in challengeDays"/u)
    assert.match(page, /class="challenge-history__date"/u)
    assert.match(page, /formattedChallengeTime\(challenge\.lastActivityAt\)/u)
    assert.match(page, /--timeline-gutter:\s*38px/u)
    assert.match(page, /row-gap:\s*var\(--timeline-gutter\)/u)
    assert.match(page, /gap:\s*calc\(var\(--timeline-gutter\) \* 2\.5\)/u)
    assert.match(page, /IntersectionObserver/u)
    assert.match(page, /limit:\s*6/u)
    assert.doesNotMatch(dashboard, /NOT EXISTS/u)
    assert.match(page, /:key="challenge\.id"/u)
    assert.match(page, /known = new Set\(dashboard\.value\.challenges\.map\(challenge => challenge\.id\)\)/u)
    assert.match(dashboard, /runs\.slice\(0, limit\)/u)
    assert.match(dashboard, /description:\s*challenge\.description/u)
    assert.match(dashboard, /FROM learner_run_questions/u)
    const challengeProgress = await read('../server/api/learner/challenge-progress.get.ts')
    const challengeProgressDialog = await read('../app/components/learner/ChallengeProgressDialog.vue')
    assert.match(challengeProgress, /is_review=0/u)
    assert.match(challengeProgress, /COALESCE\(completed_at, last_answered_at\)/u)
    assert.match(challengeProgress, /last_answered_at IS NOT NULL/u)
    assert.doesNotMatch(challengeProgress, /AND completed_at IS NOT NULL/u)
    assert.match(challengeProgressDialog, /Pourcentage de réussite/u)
    assert.doesNotMatch(challengeProgressDialog, /Nombre d’erreurs/u)
    assert.doesNotMatch(challengeProgressDialog, /<div class="challenge-progress-chart challenge-progress-chart--errors">/u)
    assert.match(challengeProgressDialog, /challenge-progress-chart/u)
    const wizard = await read('../app/components/challenge/WizardChallengeWorkspace.vue')
    const directChallengePage = await read('../app/pages/defi/[code].vue')
    const progress = await read('../server/utils/learner-progress.ts')
    assert.match(wizard, /savedChallengeDescription/u)
    assert.match(wizard, /challengePresetTrackingTitle/u)
    assert.match(wizard, /challengePresetTrackingDescription/u)
    assert.match(wizard, /sourcePresetId/u)
    assert.match(wizard, /savedChallengeTitle \|\| ui\('Verbes du défi'\)/u)
    assert.match(wizard, /wizard-step__loaded-description/u)
    assert.doesNotMatch(wizard, /loaded-challenge-intro/u)
    assert.match(wizard, /goToStep\(1\)/u)
    assert.match(wizard, /initialCode/u)
    assert.match(directChallengePage, /WizardChallengeWorkspace/u)
    assert.match(progress, /description:\s*_description/u)
    assert.match(dashboard, /f\.question_json IS NOT NULL/u)
    assert.match(dashboard, /f\.incorrect_count > 0/u)
    assert.doesNotMatch(dashboard, /filter\(form => !form\.mastered/u)
  })

  it('utilise dix questions par défaut dans les défis et les options', async () => {
    const presets = await read('../shared/data/challenge-presets.ts')
    const builder = await read('../app/composables/useChallengeBuilder.ts')
    const wizard = await read('../app/components/challenge/WizardChallengeWorkspace.vue')
    const migration = await read('../server/plugins/challenge-question-count-migration.ts')
    assert.doesNotMatch(presets, /questionCount: 20/u)
    assert.match(builder, /questionCount: 10/u)
    assert.match(wizard, /challenge\.value\.questionCount = 10/u)
    assert.match(migration, /SET question_count=10/u)
  })

  it('synthétise toutes les formes mais ne détaille que les erreurs', async () => {
    const classic = await read('../app/components/exercise/ClassicExercise.vue')
    const chat = await read('../app/components/exercise/ChatExercise.vue')
    const endpoint = await read('../server/api/learner/activity/attempt.post.ts')
    const migration = await read('../server/plugins/learner-accounts-migration.ts')
    assert.match(classic, /recordAttempt/u)
    assert.match(chat, /recordAttempt/u)
    assert.match(endpoint, /learnerFormKey/u)
    assert.match(endpoint, /INSERT INTO learner_run_forms/u)
    assert.match(endpoint, /INSERT INTO learner_run_questions/u)
    assert.match(endpoint, /const correct = validateAnswer/u)
    assert.match(endpoint, /if \(recorded && !correct\)/u)
    assert.match(endpoint, /INSERT IGNORE INTO learner_answer_attempts/u)
    assert.match(endpoint, /INSERT IGNORE INTO learner_attempt_error_tags/u)
    assert.match(endpoint, /INSERT INTO learner_skill_daily_stats/u)
    assert.match(migration, /DELETE FROM learner_answer_attempts WHERE is_correct = 1/u)
  })
})
