import type { AppLocale } from './locales'

const copies = {
  fr: {
    pageTitle: 'Compte pseudonyme', created: 'Ton compte est créé', keepCode: 'Conserve ton code de récupération', recoveryInfo: 'Il permet de récupérer ton compte sans adresse e-mail. Il ne sera plus affiché après cette étape.', username: 'Pseudonyme', recoveryCode: 'Code de récupération', codeCopied: 'Code copié', copyCode: 'Copier le code', download: 'Télécharger', continue: 'Continuer', create: 'Créer mon compte', signIn: 'Me connecter', intro: 'Créer un compte t’aide à mieux progresser : tes résultats sont mémorisés, tu peux suivre tes progrès et retravailler tes fautes. Aucun nom ni aucune adresse e-mail ne sont demandés.', chooseAction: 'Choisir une action', proposedUsername: 'Ton pseudonyme proposé', searching: 'Recherche…', unavailable: 'Indisponible', anotherUsername: 'M’en proposer un autre', choosePassword: 'Choisis un mot de passe', passwordHint: 'Au moins 10 caractères. Une petite phrase est facile à retenir.', confirmPassword: 'Confirme ton mot de passe', privacy: 'J’ai compris que le site enregistre mon pseudonyme et ma progression. Il ne demande ni mon vrai nom ni mon email et je pourrai supprimer mon compte.', creating: 'Création…', password: 'Mot de passe', signingIn: 'Connexion…',
  },
  de: {
    pageTitle: 'Pseudonymes Konto', created: 'Dein Konto wurde erstellt', keepCode: 'Bewahre deinen Wiederherstellungscode auf', recoveryInfo: 'Damit kannst du dein Konto ohne E-Mail-Adresse wiederherstellen. Nach diesem Schritt wird er nicht mehr angezeigt.', username: 'Benutzername', recoveryCode: 'Wiederherstellungscode', codeCopied: 'Code kopiert', copyCode: 'Code kopieren', download: 'Herunterladen', continue: 'Weiter', create: 'Mein Konto erstellen', signIn: 'Anmelden', intro: 'Mit einem Konto werden deine Ergebnisse gespeichert. Du kannst deinen Fortschritt verfolgen und Fehler erneut üben. Ein echter Name oder eine E-Mail-Adresse ist nicht nötig.', chooseAction: 'Aktion auswählen', proposedUsername: 'Vorgeschlagener Benutzername', searching: 'Suche…', unavailable: 'Nicht verfügbar', anotherUsername: 'Anderen vorschlagen', choosePassword: 'Passwort wählen', passwordHint: 'Mindestens 10 Zeichen. Ein kurzer Satz ist leicht zu merken.', confirmPassword: 'Passwort bestätigen', privacy: 'Ich habe verstanden, dass die Website meinen Benutzernamen und meinen Fortschritt speichert. Mein echter Name wird nicht verlangt, und ich kann mein Konto löschen.', creating: 'Konto wird erstellt…', password: 'Passwort', signingIn: 'Anmeldung…',
  },
  en: {
    pageTitle: 'Pseudonymous account', created: 'Your account has been created', keepCode: 'Keep your recovery code', recoveryInfo: 'It lets you recover your account without an email address. It will not be shown again after this step.', username: 'Username', recoveryCode: 'Recovery code', codeCopied: 'Code copied', copyCode: 'Copy code', download: 'Download', continue: 'Continue', create: 'Create my account', signIn: 'Sign in', intro: 'An account saves your results so you can track your progress and practise your mistakes again. No real name or email address is required.', chooseAction: 'Choose an action', proposedUsername: 'Suggested username', searching: 'Searching…', unavailable: 'Unavailable', anotherUsername: 'Suggest another', choosePassword: 'Choose a password', passwordHint: 'At least 10 characters. A short sentence is easy to remember.', confirmPassword: 'Confirm your password', privacy: 'I understand that the site saves my username and progress. It does not ask for my real name, and I can delete my account.', creating: 'Creating account…', password: 'Password', signingIn: 'Signing in…',
  },
  it: {
    pageTitle: 'Account con pseudonimo', created: 'Il tuo account è stato creato', keepCode: 'Conserva il codice di recupero', recoveryInfo: 'Permette di recuperare l’account senza indirizzo e-mail. Non verrà più mostrato dopo questo passaggio.', username: 'Pseudonimo', recoveryCode: 'Codice di recupero', codeCopied: 'Codice copiato', copyCode: 'Copia il codice', download: 'Scarica', continue: 'Continua', create: 'Crea il mio account', signIn: 'Accedi', intro: 'Un account salva i risultati, permette di seguire i progressi e di esercitarsi di nuovo sugli errori. Non sono richiesti nome reale né indirizzo e-mail.', chooseAction: 'Scegli un’azione', proposedUsername: 'Pseudonimo proposto', searching: 'Ricerca…', unavailable: 'Non disponibile', anotherUsername: 'Proponine un altro', choosePassword: 'Scegli una password', passwordHint: 'Almeno 10 caratteri. Una breve frase è facile da ricordare.', confirmPassword: 'Conferma la password', privacy: 'Ho capito che il sito salva il mio pseudonimo e i miei progressi. Non chiede il mio vero nome e potrò eliminare l’account.', creating: 'Creazione…', password: 'Password', signingIn: 'Accesso…',
  },
  es: {
    pageTitle: 'Cuenta con seudónimo', created: 'Tu cuenta ha sido creada', keepCode: 'Guarda tu código de recuperación', recoveryInfo: 'Permite recuperar tu cuenta sin dirección de correo electrónico. No volverá a mostrarse después de este paso.', username: 'Seudónimo', recoveryCode: 'Código de recuperación', codeCopied: 'Código copiado', copyCode: 'Copiar el código', download: 'Descargar', continue: 'Continuar', create: 'Crear mi cuenta', signIn: 'Iniciar sesión', intro: 'Una cuenta guarda tus resultados para que puedas seguir tu progreso y volver a practicar tus errores. No se pide ningún nombre real ni correo electrónico.', chooseAction: 'Elegir una acción', proposedUsername: 'Seudónimo propuesto', searching: 'Buscando…', unavailable: 'No disponible', anotherUsername: 'Proponer otro', choosePassword: 'Elige una contraseña', passwordHint: 'Al menos 10 caracteres. Una frase corta es fácil de recordar.', confirmPassword: 'Confirma tu contraseña', privacy: 'Entiendo que el sitio guarda mi seudónimo y mi progreso. No pide mi nombre real y podré eliminar mi cuenta.', creating: 'Creando…', password: 'Contraseña', signingIn: 'Iniciando sesión…',
  },
} as const

export function learnerAuthCopy(locale: AppLocale) {
  return copies[locale]
}
