const ANALYTICS_CONSENT_COOKIE_NAME = "tatitotu_analytics_consent";
const ANALYTICS_CONSENT_VERSION = "v1";
const ANALYTICS_CONSENT_ACCEPTED = `accepted-${ANALYTICS_CONSENT_VERSION}`;
const ANALYTICS_CONSENT_REFUSED = `refused-${ANALYTICS_CONSENT_VERSION}`;

export { ANALYTICS_CONSENT_ACCEPTED as A, ANALYTICS_CONSENT_COOKIE_NAME as a, ANALYTICS_CONSENT_REFUSED as b };
//# sourceMappingURL=analytics-consent.mjs.map
