const copies = {
  fr: {
    discover: "Visite guid\xE9e",
    navLabel: "Visite guid\xE9e",
    welcomeTitle: "Bienvenue sur le nouveau TATITOTU",
    welcomeBody: "Toujours 100% gratuit et sans publicit\xE9.",
    quickTitle: "Visite rapide",
    quickMeta: "Environ 1 minute",
    fullTitle: "Visite compl\xE8te",
    fullMeta: "Environ 3 minutes",
    later: "Plus tard",
    next: "Suivant",
    previous: "Pr\xE9c\xE9dent",
    finish: "Terminer",
    close: "Quitter la visite",
    progress: "{{current}} sur {{total}}",
    homeTitle: "Trois fa\xE7ons de commencer",
    homeDescription: "Reprends un d\xE9fi re\xE7u, choisis un d\xE9fi tout fait ou construis le tien.",
    buildTitle: "Construire un nouveau d\xE9fi",
    buildDescription: "Ce bouton permet de cr\xE9er son propre d\xE9fi de conjugaison.",
    stepsTitle: "Une cr\xE9ation en 4 \xE9tapes",
    stepsDescription: "Construction du d\xE9fi par \xE9tapes pour plus de lisibilit\xE9.",
    presetsTitle: "Les d\xE9fis tout faits",
    presetsDescription: "Ils pr\xE9parent imm\xE9diatement une s\xE9lection adapt\xE9e \xE0 un niveau ou \xE0 un objectif.",
    verbsTitle: "1 \xB7 Choisir les verbes",
    verbsDescription: "S\xE9lectionne ici les verbes \xE0 entrainer",
    tensesTitle: "2 \xB7 Choisir les modes et les temps",
    tensesDescription: "S\xE9lectionne ici les temps \xE0 entrainer",
    optionsTitle: "3 \xB7 R\xE9gler les options",
    optionsDescription: "R\xE9gle ici les diff\xE9rentes possibilit\xE9s de s'exercer",
    complementsTitle: "Nouveau : les compl\xE9ments d\u2019objets",
    complementsDescription: "Production de phrases compl\xE8tes, par exemple : \xAB Il mange <mark>une pomme</mark>. \xBB",
    previewTitle: "Un aper\xE7u en direct",
    previewDescription: "Pendant les r\xE9glages, un exemple de question et sa r\xE9ponse attendue se mettent \xE0 jour automatiquement.",
    createTitle: "4 \xB7 Utiliser le d\xE9fi",
    createDescription: "Le m\xEAme d\xE9fi peut \xEAtre r\xE9alis\xE9 de quatre mani\xE8res :<ol><li>En mode classique</li><li>Avec un coach virtuel</li><li>Sur papier</li><li>En le partageant avec d\u2019autres personnes</li></ol>",
    classicTitle: "1 \xB7 En mode classique",
    classicDescription: "La fa\xE7on la plus imm\xE9diate de s'entrainer. L'\xE9l\xE8ve r\xE9pond \xE0 une question et re\xE7oit la correction. 2 r\xE9ponses possibles, bilan \xE0 la fin.",
    correctionTitle: "Une correction imm\xE9diate",
    correctionDescription: "La bonne r\xE9ponse appara\xEEt, avec une explication grammaticale lorsque c\u2019est utile.",
    coachTitle: "2 \xB7 En mode coaching",
    coachDescription: "Les coaches proposent une mani\xE8re diff\xE9rente d\u2019encourager et d\u2019expliquer.",
    chatTitle: "Le chat",
    chatDescription: "L\u2019exercice prend la forme d\u2019une discussion.",
    helpTitle: "Une aide li\xE9e \xE0 la question",
    helpDescription: "Le panneau explique le verbe, la r\xE8gle et la construction de la r\xE9ponse.",
    printTitle: "3 \xB7 En mode fiche imprimable",
    printDescription: "Personnalisation de la fiche et de son corrig\xE9, disponibles aux formats PDF ou Word.",
    shareTitle: "Partager le d\xE9fi",
    shareDescription: "Cr\xE9er un code de 8 caract\xE8res permet de retrouver plus tard le d\xE9fi ou de le partager avec d\u2019autres personnes. Id\xE9al pour le partager avec les \xE9l\xE8ves d'une classe.",
    resumeTitle: "Reprendre le d\xE9fi",
    resumeDescription: "Plus tard, l\u2019\xE9l\xE8ve colle le code re\xE7u dans la page d'accueil et retrouve imm\xE9diatement le d\xE9fi. Les anciens codes restent valables.",
    falcTitle: "Le mode FALC",
    falcDescription: "FALC veut dire <strong>Facile \xE0 lire et \xE0 comprendre</strong>. Ce mode affiche seulement l\u2019essentiel, id\xE9al pour les personnes dont la lecture repr\xE9sente un effort intense.",
    accountTitle: "Nouveau : un espace pour suivre tes progr\xE8s",
    accountDescription: "Avec \xAB Connexion \xBB, tu peux cr\xE9er gratuitement un compte pour enregistrer tes r\xE9sultats et suivre tes progr\xE8s.",
    completedTitle: "Bon travail !",
    completedDescription: "Tu connais maintenant le parcours. Tu peux relancer cette visite \xE0 tout moment avec \xAB Visite guid\xE9e \xBB."
  },
  de: {
    discover: "Gef\xFChrte Tour",
    navLabel: "Gef\xFChrte Tour",
    welcomeTitle: "Willkommen beim neuen TATITOTU",
    welcomeBody: "Die Website wurde verbessert. Sie bleibt zu 100 % kostenlos und werbefrei. Es ist kein Konto erforderlich.",
    quickTitle: "Kurze F\xFChrung",
    quickMeta: "Etwa 1 Minute",
    fullTitle: "Vollst\xE4ndige F\xFChrung",
    fullMeta: "Etwa 3 Minuten",
    later: "Sp\xE4ter",
    next: "Weiter",
    previous: "Zur\xFCck",
    finish: "Beenden",
    close: "F\xFChrung schlie\xDFen",
    progress: "{{current}} von {{total}}",
    homeTitle: "Drei M\xF6glichkeiten zum Start",
    homeDescription: "\xD6ffne eine erhaltene Aufgabe, w\xE4hle eine fertige Aufgabe oder erstelle deine eigene.",
    buildTitle: "Eine neue Aufgabe erstellen",
    buildDescription: "Mit dieser Schaltfl\xE4che kannst du deine eigene Konjugationsaufgabe erstellen.",
    stepsTitle: "Erstellung in 4 Schritten",
    stepsDescription: "Die Aufgabe wird zur besseren \xDCbersicht Schritt f\xFCr Schritt erstellt.",
    presetsTitle: "Fertige Aufgaben",
    presetsDescription: "Sie stellen sofort eine Auswahl zusammen, die zu einem Niveau oder Lernziel passt.",
    verbsTitle: "1 \xB7 Verben w\xE4hlen",
    verbsDescription: "W\xE4hle hier die Verben aus, die du \xFCben m\xF6chtest.",
    tensesTitle: "2 \xB7 Modi und Zeiten w\xE4hlen",
    tensesDescription: "W\xE4hle hier die Zeiten aus, die du \xFCben m\xF6chtest.",
    optionsTitle: "3 \xB7 Optionen einstellen",
    optionsDescription: "Stelle hier die verschiedenen \xDCbungsm\xF6glichkeiten ein.",
    complementsTitle: "Neu: Objekterg\xE4nzungen",
    complementsDescription: "Bilde vollst\xE4ndige S\xE4tze, zum Beispiel: \u201EIl mange <mark>une pomme</mark>.\u201C",
    previewTitle: "Live-Vorschau",
    previewDescription: "W\xE4hrend der Einstellungen werden eine Beispielfrage und die erwartete Antwort automatisch aktualisiert.",
    createTitle: "4 \xB7 Aufgabe verwenden",
    createDescription: "Dieselbe Aufgabe kann auf vier Arten bearbeitet werden:<ol><li>Im klassischen Modus</li><li>Mit einem virtuellen Coach</li><li>Auf Papier</li><li>Indem du sie mit anderen Personen teilst</li></ol>",
    classicTitle: "1 \xB7 Im klassischen Modus",
    classicDescription: "Die direkteste Art zu \xFCben. Die lernende Person beantwortet eine Frage und erh\xE4lt die Korrektur. Zwei Versuche sind m\xF6glich, am Ende folgt eine Auswertung.",
    correctionTitle: "Sofortige Korrektur",
    correctionDescription: "Die richtige Antwort erscheint bei Bedarf mit einer grammatischen Erkl\xE4rung.",
    coachTitle: "2 \xB7 Im Coaching-Modus",
    coachDescription: "Die Coaches ermutigen und erkl\xE4ren auf unterschiedliche Weise.",
    chatTitle: "Der Chat",
    chatDescription: "Die \xDCbung findet in Form eines Gespr\xE4chs statt.",
    helpTitle: "Hilfe passend zur Frage",
    helpDescription: "Das Fenster erkl\xE4rt das Verb, die Regel und den Aufbau der Antwort.",
    printTitle: "3 \xB7 Als ausdruckbares Arbeitsblatt",
    printDescription: "Arbeitsblatt und L\xF6sung lassen sich anpassen und als PDF oder Word-Datei ausgeben.",
    shareTitle: "Aufgabe teilen",
    shareDescription: "Mit einem Code aus 8 Zeichen kannst du die Aufgabe sp\xE4ter wiederfinden oder mit anderen teilen. Ideal, um sie mit den Sch\xFClerinnen und Sch\xFClern einer Klasse zu teilen.",
    resumeTitle: "Aufgabe wiederaufnehmen",
    resumeDescription: "Sp\xE4ter f\xFCgt die lernende Person den erhaltenen Code auf der Startseite ein und findet die Aufgabe sofort wieder. Alte Codes bleiben g\xFCltig.",
    falcTitle: "Leichte Sprache",
    falcDescription: "FALC bedeutet <strong>leicht zu lesen und zu verstehen</strong>. Dieser Modus zeigt nur das Wichtigste und ist ideal f\xFCr Menschen, f\xFCr die Lesen eine gro\xDFe Anstrengung bedeutet.",
    accountTitle: "Neu: ein Bereich f\xFCr deinen Lernfortschritt",
    accountDescription: "\xDCber \u201EAnmelden\u201C kannst du kostenlos ein Konto erstellen, um deine Ergebnisse zu speichern und deinen Fortschritt zu verfolgen.",
    completedTitle: "Gute Arbeit!",
    completedDescription: "Du kennst jetzt den Ablauf. \xDCber \u201EGef\xFChrte Tour\u201C kannst du ihn jederzeit erneut ansehen."
  },
  en: {
    discover: "Guided tour",
    navLabel: "Guided tour",
    welcomeTitle: "Welcome to the new TATITOTU",
    welcomeBody: "The site has been improved. It remains 100% free and ad-free. No account is required.",
    quickTitle: "Quick tour",
    quickMeta: "About 1 minute",
    fullTitle: "Full tour",
    fullMeta: "About 3 minutes",
    later: "Later",
    next: "Next",
    previous: "Previous",
    finish: "Finish",
    close: "Leave the tour",
    progress: "{{current}} of {{total}}",
    homeTitle: "Three ways to begin",
    homeDescription: "Resume a received challenge, choose a ready-made one, or build your own.",
    buildTitle: "Build a new challenge",
    buildDescription: "This button lets you create your own conjugation challenge.",
    stepsTitle: "Create it in 4 steps",
    stepsDescription: "The challenge is built step by step for greater clarity.",
    presetsTitle: "Ready-made challenges",
    presetsDescription: "They instantly prepare a selection suited to a level or goal.",
    verbsTitle: "1 \xB7 Choose verbs",
    verbsDescription: "Select the verbs you want to practise here.",
    tensesTitle: "2 \xB7 Choose moods and tenses",
    tensesDescription: "Select the tenses you want to practise here.",
    optionsTitle: "3 \xB7 Set the options",
    optionsDescription: "Set the different ways to practise here.",
    complementsTitle: "New: object complements",
    complementsDescription: "Create complete sentences, for example: \u201CIl mange <mark>une pomme</mark>.\u201D",
    previewTitle: "Live preview",
    previewDescription: "As you adjust the settings, a sample question and its expected answer update automatically.",
    createTitle: "4 \xB7 Use the challenge",
    createDescription: "The same challenge can be completed in four ways:<ol><li>In classic mode</li><li>With a virtual coach</li><li>On paper</li><li>By sharing it with other people</li></ol>",
    classicTitle: "1 \xB7 In classic mode",
    classicDescription: "The most direct way to practise. The learner answers a question and receives the correction. Two attempts are allowed, with a summary at the end.",
    correctionTitle: "Immediate feedback",
    correctionDescription: "The correct answer appears with a grammar explanation when useful.",
    coachTitle: "2 \xB7 In coaching mode",
    coachDescription: "The coaches offer different ways to encourage and explain.",
    chatTitle: "The chat",
    chatDescription: "The exercise takes the form of a conversation.",
    helpTitle: "Help linked to the question",
    helpDescription: "The panel explains the verb, the rule and how to build the answer.",
    printTitle: "3 \xB7 As a printable worksheet",
    printDescription: "Customise the worksheet and its answer key, available as PDF or Word files.",
    shareTitle: "Share the challenge",
    shareDescription: "An 8-character code lets you retrieve the challenge later or share it with other people. Ideal for sharing it with the students in a class.",
    resumeTitle: "Resume the challenge",
    resumeDescription: "Later, the learner pastes the received code on the home page and immediately retrieves the challenge. Older codes remain valid.",
    falcTitle: "Easy-read mode",
    falcDescription: "FALC means <strong>easy to read and understand</strong>. This mode shows only the essentials and is ideal for people who find reading intensely demanding.",
    accountTitle: "New: a space to track your progress",
    accountDescription: "Use \u201CSign in\u201D to create a free account, save your results and track your progress.",
    completedTitle: "Good work!",
    completedDescription: "You now know the workflow. You can restart this tour at any time with \u201CGuided tour\u201D."
  },
  it: {
    discover: "Visita guidata",
    navLabel: "Visita guidata",
    welcomeTitle: "Benvenuto nel nuovo TATITOTU",
    welcomeBody: "Il sito \xE8 stato migliorato. Rimane gratuito al 100% e senza pubblicit\xE0. Non \xE8 necessario alcun account.",
    quickTitle: "Visita rapida",
    quickMeta: "Circa 1 minuto",
    fullTitle: "Visita completa",
    fullMeta: "Circa 3 minuti",
    later: "Pi\xF9 tardi",
    next: "Avanti",
    previous: "Indietro",
    finish: "Termina",
    close: "Esci dalla visita",
    progress: "{{current}} di {{total}}",
    homeTitle: "Tre modi per iniziare",
    homeDescription: "Riprendi una sfida ricevuta, scegline una pronta o costruisci la tua.",
    buildTitle: "Crea una nuova sfida",
    buildDescription: "Questo pulsante permette di creare la propria sfida di coniugazione.",
    stepsTitle: "Creazione in 4 tappe",
    stepsDescription: "La sfida viene costruita per tappe, per una maggiore chiarezza.",
    presetsTitle: "Le sfide gi\xE0 pronte",
    presetsDescription: "Preparano subito una selezione adatta a un livello o a un obiettivo.",
    verbsTitle: "1 \xB7 Scegliere i verbi",
    verbsDescription: "Seleziona qui i verbi da allenare.",
    tensesTitle: "2 \xB7 Scegliere modi e tempi",
    tensesDescription: "Seleziona qui i tempi da allenare.",
    optionsTitle: "3 \xB7 Impostare le opzioni",
    optionsDescription: "Imposta qui le diverse possibilit\xE0 di esercitazione.",
    complementsTitle: "Novit\xE0: complementi oggetto",
    complementsDescription: "Produci frasi complete, per esempio: \xAB Il mange <mark>une pomme</mark>. \xBB",
    previewTitle: "Anteprima in tempo reale",
    previewDescription: "Durante le impostazioni, una domanda di esempio e la risposta attesa si aggiornano automaticamente.",
    createTitle: "4 \xB7 Usare la sfida",
    createDescription: "La stessa sfida pu\xF2 essere svolta in quattro modi:<ol><li>In modalit\xE0 classica</li><li>Con un coach virtuale</li><li>Su carta</li><li>Condividendola con altre persone</li></ol>",
    classicTitle: "1 \xB7 In modalit\xE0 classica",
    classicDescription: "Il modo pi\xF9 immediato per allenarsi. L\u2019allievo risponde a una domanda e riceve la correzione. Sono disponibili due tentativi, con un bilancio finale.",
    correctionTitle: "Correzione immediata",
    correctionDescription: "Appare la risposta corretta, con una spiegazione grammaticale se utile.",
    coachTitle: "2 \xB7 In modalit\xE0 coaching",
    coachDescription: "I coach propongono modi diversi di incoraggiare e spiegare.",
    chatTitle: "La chat",
    chatDescription: "L\u2019esercizio assume la forma di una conversazione.",
    helpTitle: "Un aiuto legato alla domanda",
    helpDescription: "Il pannello spiega il verbo, la regola e la costruzione della risposta.",
    printTitle: "3 \xB7 Come scheda stampabile",
    printDescription: "Personalizza la scheda e le soluzioni, disponibili nei formati PDF o Word.",
    shareTitle: "Condividere la sfida",
    shareDescription: "Un codice di 8 caratteri permette di ritrovare la sfida in seguito o di condividerla con altre persone. \xC8 ideale per condividerla con gli alunni di una classe.",
    resumeTitle: "Riprendere la sfida",
    resumeDescription: "In seguito, l\u2019allievo incolla il codice ricevuto nella pagina iniziale e ritrova subito la sfida. I vecchi codici restano validi.",
    falcTitle: "Modalit\xE0 di facile lettura",
    falcDescription: "FALC significa <strong>facile da leggere e da capire</strong>. Questa modalit\xE0 mostra solo l\u2019essenziale ed \xE8 ideale per le persone per cui leggere richiede uno sforzo intenso.",
    accountTitle: "Novit\xE0: uno spazio per seguire i tuoi progressi",
    accountDescription: "Con \xAB Connessione \xBB puoi creare gratuitamente un account, salvare i risultati e seguire i tuoi progressi.",
    completedTitle: "Buon lavoro!",
    completedDescription: "Ora conosci il percorso. Puoi riavviare questa visita in qualsiasi momento con \xAB Visita guidata \xBB."
  },
  es: {
    discover: "Visita guiada",
    navLabel: "Visita guiada",
    welcomeTitle: "Bienvenido al nuevo TATITOTU",
    welcomeBody: "El sitio ha sido mejorado. Sigue siendo 100 % gratuito y sin publicidad. No se necesita ninguna cuenta.",
    quickTitle: "Visita r\xE1pida",
    quickMeta: "Aproximadamente 1 minuto",
    fullTitle: "Visita completa",
    fullMeta: "Aproximadamente 3 minutos",
    later: "M\xE1s tarde",
    next: "Siguiente",
    previous: "Anterior",
    finish: "Terminar",
    close: "Salir de la visita",
    progress: "{{current}} de {{total}}",
    homeTitle: "Tres formas de empezar",
    homeDescription: "Retoma un desaf\xEDo recibido, elige uno preparado o crea el tuyo.",
    buildTitle: "Crear un nuevo desaf\xEDo",
    buildDescription: "Este bot\xF3n permite crear tu propio desaf\xEDo de conjugaci\xF3n.",
    stepsTitle: "Creaci\xF3n en 4 etapas",
    stepsDescription: "El desaf\xEDo se construye por etapas para que resulte m\xE1s claro.",
    presetsTitle: "Desaf\xEDos preparados",
    presetsDescription: "Preparan al instante una selecci\xF3n adaptada a un nivel o a un objetivo.",
    verbsTitle: "1 \xB7 Elegir los verbos",
    verbsDescription: "Selecciona aqu\xED los verbos que quieres practicar.",
    tensesTitle: "2 \xB7 Elegir modos y tiempos",
    tensesDescription: "Selecciona aqu\xED los tiempos que quieres practicar.",
    optionsTitle: "3 \xB7 Configurar las opciones",
    optionsDescription: "Configura aqu\xED las distintas posibilidades para practicar.",
    complementsTitle: "Nuevo: complementos de objeto",
    complementsDescription: "Produce frases completas, por ejemplo: \xAB Il mange <mark>une pomme</mark>. \xBB",
    previewTitle: "Vista previa en directo",
    previewDescription: "Durante la configuraci\xF3n, una pregunta de ejemplo y su respuesta esperada se actualizan autom\xE1ticamente.",
    createTitle: "4 \xB7 Utilizar el desaf\xEDo",
    createDescription: "El mismo desaf\xEDo puede realizarse de cuatro maneras:<ol><li>En modo cl\xE1sico</li><li>Con un coach virtual</li><li>En papel</li><li>Compartiendo con otras personas</li></ol>",
    classicTitle: "1 \xB7 En modo cl\xE1sico",
    classicDescription: "La forma m\xE1s directa de practicar. El alumno responde a una pregunta y recibe la correcci\xF3n. Hay dos intentos posibles y un balance final.",
    correctionTitle: "Correcci\xF3n inmediata",
    correctionDescription: "Aparece la respuesta correcta con una explicaci\xF3n gramatical cuando es \xFAtil.",
    coachTitle: "2 \xB7 En modo coaching",
    coachDescription: "Los coaches proponen distintas maneras de animar y explicar.",
    chatTitle: "El chat",
    chatDescription: "El ejercicio adopta la forma de una conversaci\xF3n.",
    helpTitle: "Una ayuda vinculada a la pregunta",
    helpDescription: "El panel explica el verbo, la regla y la construcci\xF3n de la respuesta.",
    printTitle: "3 \xB7 Como ficha imprimible",
    printDescription: "Personaliza la ficha y sus soluciones, disponibles en formato PDF o Word.",
    shareTitle: "Compartir el desaf\xEDo",
    shareDescription: "Un c\xF3digo de 8 caracteres permite recuperar el desaf\xEDo m\xE1s tarde o compartirlo con otras personas. Es ideal para compartirlo con el alumnado de una clase.",
    resumeTitle: "Retomar el desaf\xEDo",
    resumeDescription: "M\xE1s tarde, el alumno pega el c\xF3digo recibido en la p\xE1gina de inicio y recupera inmediatamente el desaf\xEDo. Los c\xF3digos antiguos siguen siendo v\xE1lidos.",
    falcTitle: "Modo de lectura f\xE1cil",
    falcDescription: "FALC significa <strong>f\xE1cil de leer y comprender</strong>. Este modo muestra solo lo esencial y es ideal para las personas para quienes leer supone un esfuerzo intenso.",
    accountTitle: "Nuevo: un espacio para seguir tus progresos",
    accountDescription: "Con \xAB Conexi\xF3n \xBB puedes crear una cuenta gratuita, guardar tus resultados y seguir tus progresos.",
    completedTitle: "\xA1Buen trabajo!",
    completedDescription: "Ya conoces el recorrido. Puedes reiniciar esta visita en cualquier momento con \xAB Visita guiada \xBB."
  }
};
function guidedTourCopy(locale) {
  var _a;
  return (_a = copies[locale]) != null ? _a : copies.fr;
}

export { guidedTourCopy as g };
//# sourceMappingURL=guided-tour.mjs.map
